### ISSUE TITLE
Network Id format is incorrect

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-config-generator#12]
Inserts `"111"` should insert `111`

**Comment by arkpar** [comment]
Network id can be either a number or a string. In case of a string its hash is used.

**Comment by genesischain** [comment]
@arkpar if you try to start parity with anything but an integer it fails with an error: You might have supplied invalid parameters in config file. expected a value of type `integer`, but found a value of type `string` for the key `network.id` how do you make it use a string?

**Comment by arkpar** [comment]
I was referring to the original CLI param. I suppose config file should support the same choice and then the generator as well.

**Comment by tomusdrw** [comment]
@arkpar did you mean `--identity`? Seems that `--network-id` is just an `u64`.

**Comment by arkpar** [comment]
Right, I was thinking of `--node-key`
