### ISSUE TITLE
Idea: automatically get the data from paritytech/parity/parity/cli/mod.rs

### ISSUE THREAD

**Issue by axelchalon** [paritytech/parity-config-generator#34]
I noticed that:
- the config items aren't up-to-date (some new config parameters available in parity haven't yet been added to parity-config-generator)
- all the information (in parity-config-generator [`data.json`](https://github.com/paritytech/parity-config-generator/blob/master/src/data.json)) is basically the same as in https://github.com/paritytech/parity/blob/master/parity/cli/mod.rs -- save for the help messages that seem to have been rewritten

As such I suggest to parse [`cli/mod.rs`](https://github.com/paritytech/parity/blob/master/parity/cli/mod.rs) from the parity repo, and generate the parity-config-generator data based on the contents of this file. 

Implementation-wise:
- The `Config` struct in `cli/mod.rs` gives us the structure of the sections.
- The items in the structs give us the items of the section and their types: `Option<Bool>` ⇒ render it as a checkbox
- The default value is given to us by the corresponding line in the call to the `usage!` macro: `ARG arg_work_queue_size: (usize) = 20usize, or |c: &Config| c.mining.as_ref()?.work_queue_size.clone(),` ⇒ default value is 20.

To determine the relationship between a config entry and the command-line argument, and infer the default config entry value, I notice that the config closure always follows the same patterns:
- `|c: &Config| c.parity.as_ref()?.public_node.clone()` etc. (120 times)
- `|_| None` (35 times)
- `|c: &Config| c.rpc.as_ref()?.cors.as_ref().map(|vec| vec.join(","))` etc. (16 times)
- `|c: &Config| c.network.as_ref()?.warp.clone().map(|w| !w)` etc. (3 times)
- `|c: &Config| Some(c.stratum.is_some())` (1 time)

This also lets us display the corresponding command-line option next to the config item (https://github.com/paritytech/parity-config-generator/issues/2).

So basically it looks like we have all the information necessary to feed the config generator. This way we would have `cli/mod.rs` be the single source of truth, and parity-config-generator would need very little maintenance as its data would update automatically (and we would be sure it's up‑to‑date). We could update the data on each build, or dynamically client-side.

The only downside I see is that we would lose the sometimes more explicit help messages written in https://github.com/paritytech/parity-config-generator/blob/master/src/data.json, as well as the additional meta information of the more structured entries of `data.json` (possible values for an entry; multiselects such as the list of exposed apis; min and max values). This being said, we could get the same result if we normalize a little bit more the help messages. This metadata could be integrated in the general structure of the help messages (e.g. at the end of a help message, we could write `(min: XXX, max: YYY)`). In this same line of thought, we can already parse `can be one of` in the help messages.

In short, this looks to me like this would be doable.

What do you think? Do you think it's a good idea? Would be happy to get started on this if so. The first step could simply be a script that generates `data.json`.

@tomusdrw

**Comment by tomusdrw** [comment]
Great idea @axelchalon ! I'm all in for auto-populating `data.json` based on the rust code (maybe a tiny regex-based parser would be fast to write and easy to maintain). In such case we can still augment the generated data.json with some additional stuff like more detailed help.

**Comment by axelchalon** [comment]
You're right! We can augment the generated data.json with more explicit help messages, the possible choices and whether it's a multiselect (until we figure a way to automate this); this way we get the best of both worlds. Cool! Yes, also had a regex-based parser in mind. I'll start prototyping and I'll let you know how this goes!
