### ISSUE TITLE
Direct link to configuration file

### ISSUE THREAD

**Issue by asymmetric** [paritytech/parity-config-generator#46]
Hi,

When provisioning new machines it would be really cool if I could simply run `curl https://paritytech.github.io/parity-config-generator/#config=HASH` in one of the new machines to retrieve the parity config.

Currently I have to resort to copying a file, which requires SSH access. The new feature would make it possible to disable SSH.

**Comment by axelchalon** [comment]
I don't think this is technically possible to do with our current setup. Parity Config Generator is a static website served by GitHub pages ; to implement what you suggest we would need to have a backend to be able to serve dynamic pages.

The hash isn't a hash actually, it's the base64-encoded JSON string of the config file, so I think that if you convert it to toml you have a valid Parity config file

**Comment by tomusdrw** [comment]
Definitely possible, but the `HASH` in the URL is actually the entire config file encoded in base64 - maybe better just use this?
