### ISSUE TITLE
Fat_db boolean error

### ISSUE THREAD

**Issue by realcodywburns** [paritytech/parity-config-generator#6]
When enabling fatDB with the config tool the following is generated:

` #Enables Fat DB`
`fat_db = true`

After adding the config.toml the following error is generated when running the program:

`You might have supplied invalid parameters in config file.`
`expected a value of type `string`, but found a value of type `boolean` for the key `footprint.fat_db``

**Comment by tomusdrw** [comment]
Thanks for reporting! Should be fixed now.
