### ISSUE TITLE
Support custom chains

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-config-generator#7]

**Comment by roninkaizen** [comment]
hola, 
tester for musicoin u. a. , or how is this meant?

**Comment by tomusdrw** [comment]
Hey @roninkaizen !

Musiccoin is supported by parity, so it should be part of the dropdown (current version just doesn't have it there).

This issue is about supporting custom chainfiles (so not only you can select a chain from a dropdown, but also you can specify a custom one in the input) in the code - will require a different React component to do that.
